### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by downthecrop** [downthecrop/web-ftp-client#1]
- [x] Drag and Drop from Server to Local
- [x] Control+H hidden filese
- [x] Cleanup Electron check in index.html
- [ ] Notify replace files (if the file with that name already exists)
- [ ] Browse file system for PPK file instead of copy paste
- [ ] Complex drag and drop dialogue (Replace/)
- [x] Fix Create new Directory box remaining alive
- [ ] Drag from Windows Explorer into server
- [x] Control Click multi file select

**Comment by downthecrop** [comment]
Possible option for file icons https://fileicons.org/?view=classic&mode=dark

**Comment by downthecrop** [comment]
https://ourcodeworld.com/articles/read/262/how-to-build-publish-a-release-distribution-of-an-electron-application-with-the-cli
